openapi: 3.1.0
x-stoplight:
  id: 91a4ao3uk9mo2
info:
  title: Import export Overview
  version: '0.6'
  description: |-
    # Overview import export api documentation

    The HTTP status codes returned by the endpoints follow these rules:
    - If the flow is correct, returns positive response code
    - If the flow is incorrect, returns negative response code 
    - If the flow breaks for some reason (DB connection, malformed input, etc..), returns negative response
  contact:
    email: internal-dev-team@icadsistemi.com
    name: Dev team internal
servers:
  - url: 'https://mxp-import-export-ov.dev.icadsistemi.com/v1'
    description: development
  - url: 'https://mxp-import-export-ov.prod.icadsistemi.com/v1'
    description: production
paths:
  /export/fuelstations/circuits:
    get:
      summary: Get fuelstations circuits
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  x-stoplight:
                    id: qpkjieelktla6
                  type: object
                  properties:
                    fuelstation_name:
                      type: string
                      x-stoplight:
                        id: fggaxgd57gj57
                    iscode:
                      type: string
                      x-stoplight:
                        id: c99cnlx7uod95
                    supplier_name:
                      type: string
                      x-stoplight:
                        id: sjac0mstt9nqc
              examples:
                Example 1:
                  value:
                    - fuelstation_name: string
                      iscode: string
                      supplier_name: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '422':
          description: Unprocessable Entity (WebDAV)
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
      operationId: get-fuelstations-circuits
      description: Used to get all enabled fuelstations circuits
      parameters: []
      tags:
        - fuelstations
  /export/supplies/payments/circuits:
    get:
      summary: Get payment supplies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  x-stoplight:
                    id: 6rz6q7a7rvzpu
                  type: object
                  properties:
                    payment_id:
                      type: integer
                      x-stoplight:
                        id: n3vtkc2pi2tqg
                      description: System payment id
                    fuelstation_name:
                      type: string
                      x-stoplight:
                        id: cz3wsnszjc6ke
                    iscode:
                      type: string
                      x-stoplight:
                        id: 42a1a3p1si83w
                    supplier_name:
                      type: string
                      x-stoplight:
                        id: 7gmtuucyzixm4
                    datetime:
                      type: string
                      x-stoplight:
                        id: w7l9wlxthz8t4
                      description: date time format in local time
                    card_name:
                      type: string
                      x-stoplight:
                        id: 858hju9eoym6u
                    payment_mode:
                      type: string
                      x-stoplight:
                        id: 1fhvtm9t0dm34
                    amount:
                      type: number
                      x-stoplight:
                        id: jr1wu7zqgwwvi
                    supplies:
                      type: array
                      x-stoplight:
                        id: gl5qcjez2wwex
                      items:
                        x-stoplight:
                          id: 953yqy8qnzj8e
                        type: object
                        properties:
                          authorization_code:
                            type: string
                            x-stoplight:
                              id: bs4ft7zekdu5k
                          article:
                            type: string
                            x-stoplight:
                              id: hjddmpeihlcub
                          unit_price:
                            type: number
                            x-stoplight:
                              id: 3dyamvx1t8jel
                          ticket_number:
                            type: integer
                            x-stoplight:
                              id: wy9qcjf3cai8q
                          pump_number:
                            type: integer
                            x-stoplight:
                              id: entlewabvnfyx
                          vat:
                            type: number
                            x-stoplight:
                              id: lxfnb3laj4ap8
                          supply_id:
                            type: integer
                            x-stoplight:
                              id: 5ek474pqv8cr0
                            description: System supply id
                          quantity:
                            type: number
                            x-stoplight:
                              id: 7h4urgdaz4or3
                          card_number:
                            type: string
                            x-stoplight:
                              id: zhnoba96kcltj
                            description: Last 4 chars from card number
                  required:
                    - fuelstation_name
                    - iscode
                    - supplier_name
                    - datetime
                    - card_name
                    - payment_mode
                    - amount
              examples:
                Example 2:
                  value:
                    - payment_id: 0
                      fuelstation_name: string
                      iscode: string
                      supplier_name: string
                      datetime: string
                      card_name: string
                      payment_mode: string
                      amount: 0
                      supplies:
                        - authorization_code: string
                          article: string
                          unit_price: 0
                          ticket_number: 0
                          pump_number: 0
                          vat: 0
                          supply_id: 0
                          quantity: 0
                          card_number: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '422':
          description: Unprocessable Entity (WebDAV)
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
      operationId: get-circuits-payments-supplies
      parameters:
        - schema:
            type: integer
          in: query
          name: start_datetime
          required: true
          description: 'unix time format '
        - schema:
            type: integer
          in: query
          name: end_datetime
          required: true
          description: unix time format
        - schema:
            type: boolean
          in: query
          name: only_updated_payments
          description: optionals. if true return list of circuits payments supplies updated
      description: Get circuits payments supplies
      tags:
        - supplies
components:
  schemas: {}
  securitySchemes:
    develop:
      type: oauth2
      flows:
        clientCredentials:
          refreshUrl: ''
          scopes: {}
          tokenUrl: 'https://dub-dev-icadsistemi-users.auth.eu-west-1.amazoncognito.com/token'
    production:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://dub-prod-icadsistemi-users.auth.eu-west-1.amazoncognito.com/token'
          refreshUrl: ''
          scopes: {}
  responses: {}
tags:
  - name: import export
security:
  - develop: []
  - production: []
