openapi: 3.1.0
x-stoplight:
  id: 91a4ao3uk9mo2
info:
  title: Import export Overview
  version: '0.10'
  description: |-
    # Overview import export api documentation

    The HTTP status codes returned by the endpoints follow these rules:
    - If the flow is correct, returns positive response code
    - If the flow is incorrect, returns negative response code 
    - If the flow breaks for some reason (DB connection, malformed input, etc..), returns negative response
  contact:
    email: internal-dev-team@icadsistemi.com
    name: Dev team internal
servers:
  - url: 'https://mxp-import-export-ov.dev.icadsistemi.com/v1'
    description: development
  - url: 'https://mxp-import-export-ov.prod.icadsistemi.com/v1'
    description: production
paths:
  /export/circuits/fuelstations:
    get:
      summary: Get fuelstations for enabled circuits
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  x-stoplight:
                    id: qpkjieelktla6
                  type: object
                  properties:
                    fuelstation_name:
                      type: string
                      x-stoplight:
                        id: fggaxgd57gj57
                    iscode:
                      type: string
                      x-stoplight:
                        id: c99cnlx7uod95
                    supplier_name:
                      type: string
                      x-stoplight:
                        id: sjac0mstt9nqc
              examples:
                Example 1:
                  value:
                    - fuelstation_name: string
                      iscode: string
                      supplier_name: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '422':
          description: Unprocessable Entity (WebDAV)
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
      operationId: get-fuelstations-circuits
      description: Get all enabled fuelstations for enabled circuits
      parameters: []
      tags:
        - fuelstations
    parameters: []
  /export/circuits/payments:
    get:
      summary: Get payments with supplies for enabled circuits
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  x-stoplight:
                    id: 6rz6q7a7rvzpu
                  type: object
                  properties:
                    payment_id:
                      type: integer
                      x-stoplight:
                        id: n3vtkc2pi2tqg
                      description: System payment id
                    fuelstation_name:
                      type: string
                      x-stoplight:
                        id: cz3wsnszjc6ke
                      description: Fuel station name
                    iscode:
                      type: string
                      x-stoplight:
                        id: 42a1a3p1si83w
                      description: IS code assigned to the fuel station
                    supplier_name:
                      type: string
                      x-stoplight:
                        id: 7gmtuucyzixm4
                      description: Supplier name
                    datetime:
                      type: string
                      x-stoplight:
                        id: w7l9wlxthz8t4
                      description: Transaction date time format in local time
                    card_name:
                      type: string
                      x-stoplight:
                        id: 858hju9eoym6u
                      description: Card name
                    card_number:
                      type: string
                      x-stoplight:
                        id: 2d6bh2pucc9os
                      description: Last 4 chars from card number
                    payment_mode:
                      type: string
                      x-stoplight:
                        id: 1fhvtm9t0dm34
                      description: Payment mode
                    amount:
                      type: number
                      x-stoplight:
                        id: jr1wu7zqgwwvi
                      description: Payment amount
                    authorization_code:
                      type: string
                      x-stoplight:
                        id: vcy19nvuy02rh
                      description: Unique numeric code generated by the payment card issuer during the authorization process
                    stan:
                      type: string
                      x-stoplight:
                        id: oi49prt95n3l8
                      description: System Trace Audit Number
                    supplies:
                      type: array
                      x-stoplight:
                        id: gl5qcjez2wwex
                      description: Array of supplies that were paid with this transaction
                      items:
                        x-stoplight:
                          id: 953yqy8qnzj8e
                        type: object
                        properties:
                          article_id:
                            type: integer
                            enum:
                              - 1
                              - 2
                              - 3
                              - 4
                              - 5
                              - 6
                              - 7
                              - 10
                              - 17
                              - 20
                              - 21
                              - 22
                            x-enum-varnames:
                              - Verde
                              - Diesel
                              - Benzina Spec.
                              - Gasolio Spec.
                              - AdBlue
                              - GPL
                              - Metano
                              - Not Avaiable
                              - GNL
                              - Olio Lubr.
                              - HVO
                              - L-GNC
                            x-stoplight:
                              id: my330tnclmmg9
                            description: 'Article identifier: 1 - Green Petrol, 2 - Diesel, 3 - Special Petrol, 4 - Special Diesel, 5 - AdBlue, 6 - LPG (Liquefied Petroleum Gas), 7 - Methane, 17 - LNG (Liquefied Natural Gas), 20 - Lubricating Oil, 21 - HVO (Hydrotreated Vegetable Oil), 22 - L-GNC (Liquefied Compressed Natural Gas)'
                          article:
                            type: string
                            x-stoplight:
                              id: hjddmpeihlcub
                            description: Article description
                          unit_price:
                            type: number
                            x-stoplight:
                              id: 3dyamvx1t8jel
                            description: Article unit price
                          ticket_number:
                            type: integer
                            x-stoplight:
                              id: wy9qcjf3cai8q
                            description: Ticket number assignet to the supply
                          pump_number:
                            type: integer
                            x-stoplight:
                              id: entlewabvnfyx
                            description: Pump number
                          vat:
                            type: number
                            x-stoplight:
                              id: lxfnb3laj4ap8
                            description: Article VAT
                          supply_id:
                            type: integer
                            x-stoplight:
                              id: 5ek474pqv8cr0
                            description: System supply id
                          quantity:
                            type: number
                            x-stoplight:
                              id: 7h4urgdaz4or3
                            description: Article quantity
                          supply_amount:
                            type: number
                            x-stoplight:
                              id: 159xjgu770m1r
                            description: Supply amount
              examples:
                Example 2:
                  value:
                    - value:
                        - payment_id: 0
                          fuelstation_name: string
                          iscode: string
                          supplier_name: string
                          datetime: string
                          card_name: string
                          card_number: string
                          payment_mode: string
                          amount: 0
                          authorization_code: string
                          stan: string
                          supplies:
                            - article_id: 0
                              article: string
                              unit_price: 0
                              ticket_number: 0
                              pump_number: 0
                              vat: 0
                              supply_id: 0
                              quantity: 0
                              supply_amount: 0
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '422':
          description: Unprocessable Entity (WebDAV)
        '429':
          description: Too Many Requests
        '500':
          description: Internal Server Error
      operationId: get-circuits-payments-supplies
      parameters:
        - schema:
            type: integer
          in: query
          name: start_datetime
          required: true
          description: 'unix time format '
        - schema:
            type: integer
          in: query
          name: end_datetime
          required: true
          description: unix time format
        - schema:
            type: boolean
          in: query
          name: only_updated_payments
          description: optionals. if true return list of circuits payments supplies updated
      description: Get payments with supplies for enabled circuits
      tags:
        - payments
    parameters: []
components:
  schemas: {}
  securitySchemes:
    develop:
      type: oauth2
      flows:
        clientCredentials:
          refreshUrl: ''
          scopes: {}
          tokenUrl: 'https://dub-dev-icadsistemi-users.auth.eu-west-1.amazoncognito.com/token'
    production:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://dub-prod-icadsistemi-users.auth.eu-west-1.amazoncognito.com/token'
          refreshUrl: ''
          scopes: {}
  responses: {}
tags:
  - name: import export
security:
  - develop: []
  - production: []
